import { describe, expect, test, vi } from "vitest";

import {
  normalizeAmbientTypeFields,
  compareTypeArtifacts,
  runGeneratorWithRetry,
} from "../../../scripts/check-types-drift.mjs";
import {
  HEADER,
  applyTriggerDerivedInsertOptionality,
  composeArtifact,
} from "../../../scripts/generate-supabase-types.mjs";

// A committed artifact and a freshly generated one that differ ONLY inside
// `__InternalSupabase`. Nothing in that block is schema: it reports the
// PostgREST deployment the artifact was generated against. The platform can
// change the version with no code change on our side, and the CLI's --local
// generator omits the block entirely while the hosted API emits it. Either
// difference, treated as drift, reddens CI for a reason no branch author can
// act on.
const committed = `// Generated by \`supabase gen types typescript\`.
export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.17"
  }
  public: {
    Tables: {
      wines: { Row: { id: string; status: "pending" | "applied" } }
    }
  }
}
`;

const ambientOnly = committed.replace('"14.17"', '"14.5"');

// What `supabase gen types --local` actually produces: no block at all.
const localGenerated = committed.replace(
  `  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.17"
  }
`,
  "",
);

const schemaChanged = committed.replace(
  "wines: { Row: { id: string; status: \"pending\" | \"applied\" } }",
  "wines: { Row: { id: string; lwin_id: string; status: \"pending\" | \"applied\" } }",
);

// The regression that a too-greedy normalizer hides: an enum member RENAMED,
// leaving the same number of quoted literals in the same positions. Blanking
// every quoted string makes this artifact identical to the committed one, so
// the gate would wave a real schema change straight through.
const enumValueRenamed = committed.replace('"applied"', '"reverted"');

const bothChanged = schemaChanged.replace('"14.17"', '"14.5"');

describe("types drift gate", () => {
  test("normalization erases the ambient PostgrestVersion but nothing else", () => {
    expect(normalizeAmbientTypeFields(committed)).toBe(
      normalizeAmbientTypeFields(ambientOnly),
    );
    // The rest of the artifact must survive normalization verbatim, or the
    // gate would be blind to real changes near the normalized line.
    expect(normalizeAmbientTypeFields(committed)).toContain(
      'status: "pending" | "applied"',
    );
    expect(normalizeAmbientTypeFields(committed)).not.toContain("14.17");
  });

  test("a PostgrestVersion-only difference is NOT drift", () => {
    expect(compareTypeArtifacts(committed, ambientOnly).drifted).toBe(false);
  });

  test("an artifact generated locally, with no __InternalSupabase block, is NOT drift", () => {
    // The local generator omits the block. Normalizing only the version
    // string left the block itself in the committed side, so every line after
    // it shifted and the diff read as though the whole file had changed.
    expect(compareTypeArtifacts(committed, localGenerated).drifted).toBe(false);
  });

  test("a schema difference in a locally generated artifact IS still drift", () => {
    const localWithSchemaChange = localGenerated.replace(
      'wines: { Row: { id: string; status: "pending" | "applied" } }',
      'wines: { Row: { id: string; lwin_id: string; status: "pending" | "applied" } }',
    );
    expect(compareTypeArtifacts(committed, localWithSchemaChange).drifted).toBe(true);
  });

  test("a schema difference IS drift", () => {
    const result = compareTypeArtifacts(committed, schemaChanged);
    expect(result.drifted).toBe(true);
    expect(result.diff).toContain("lwin_id");
  });

  test("a schema difference is still drift when the ambient value also moved", () => {
    // The dangerous regression: normalizing too greedily (or bailing out as
    // soon as the version differs) would let a real schema change ride in
    // behind a platform version bump.
    expect(compareTypeArtifacts(committed, bothChanged).drifted).toBe(true);
  });

  test("a renamed enum member IS drift", () => {
    // Guards against normalizing quoted literals wholesale.
    expect(compareTypeArtifacts(committed, enumValueRenamed).drifted).toBe(
      true,
    );
  });

  test("identical artifacts are not drift", () => {
    expect(compareTypeArtifacts(committed, committed).drifted).toBe(false);
  });
});

// The other half of the same rule: the gate must not fire on how the bytes
// travelled. `types:gen` fetches the body from the Management API, which
// returns it with a single trailing newline; `types:check:local` shells out to
// `supabase gen types --local`, whose stdout carries an extra one. Before
// composeArtifact normalized that, CI reported a one-character diff (a bare
// `+`) on every run, with nothing a branch author could regenerate to fix it.
describe("composeArtifact", () => {
  const body = `export type Database = {
  public: { Tables: { wines: { Row: { id: string } } } }
}
`;

  test("the two transports produce a byte-identical artifact", () => {
    expect(composeArtifact(body)).toBe(composeArtifact(`${body}\n`));
  });

  test("the artifact ends with exactly one newline", () => {
    expect(composeArtifact(`${body}\n\n\n`).endsWith("}\n")).toBe(true);
    expect(composeArtifact(body).endsWith("}\n\n")).toBe(false);
  });

  test("the committed artifact is already in normalized form", async () => {
    const { readFile } = await import("node:fs/promises");
    const committedArtifact = await readFile("src/types/database.ts", "utf8");
    expect(committedArtifact).toBe(
      composeArtifact(committedArtifact.slice(HEADER.length)),
    );
  });

  test("a body difference still survives normalization", () => {
    expect(composeArtifact(body)).not.toBe(
      composeArtifact(body.replace("wines", "vintages")),
    );
  });
});

describe("trigger-derived Insert optionality", () => {
  const generatedBody = `export type Database = {
  public: {
    Tables: {
      memberships: {
        Row: {
          workspace_membership_id: string
        }
        Insert: {
          workspace_membership_id: string
        }
        Update: {
          workspace_membership_id?: string
        }
      }
      restaurants: {
        Row: {
          workspace_id: string
        }
        Insert: {
          workspace_id: string
        }
        Update: {
          workspace_id?: string
        }
      }
      wines: {
        Row: { id: string }
        Insert: { id?: string }
        Update: { id?: string }
      }
    }
  }
}
`;

  test("changes only the two trigger-derived Insert fields", () => {
    const normalized = applyTriggerDerivedInsertOptionality(generatedBody);
    const expected = generatedBody
      .replace(
        "        Insert: {\n          workspace_membership_id: string\n",
        "        Insert: {\n          workspace_membership_id?: string\n",
      )
      .replace(
        "        Insert: {\n          workspace_id: string\n",
        "        Insert: {\n          workspace_id?: string\n",
      );
    expect(normalized).toBe(expected);
  });

  test("is idempotent for an already normalized artifact", () => {
    const normalized = applyTriggerDerivedInsertOptionality(generatedBody);
    expect(applyTriggerDerivedInsertOptionality(normalized)).toBe(normalized);
  });

  test.each([
    ["missing table", generatedBody.replace("      memberships: {\n", "")],
    [
      "missing field",
      generatedBody.replaceAll("          workspace_id: string\n", ""),
    ],
    [
      "changed field type",
      generatedBody.replace(
        "          workspace_membership_id: string\n",
        "          workspace_membership_id: string | null\n",
      ),
    ],
    [
      "duplicate field",
      generatedBody.replace(
        "        Insert: {\n          workspace_id: string\n",
        "        Insert: {\n          workspace_id: string\n          workspace_id: string\n",
      ),
    ],
    [
      "Row duplicate field with a different type",
      generatedBody.replace(
        "        Row: {\n          workspace_membership_id: string\n",
        "        Row: {\n          workspace_membership_id: string\n          workspace_membership_id: number\n",
      ),
    ],
    [
      "Insert duplicate field with a different type",
      generatedBody.replace(
        "        Insert: {\n          workspace_id: string\n",
        "        Insert: {\n          workspace_id: string\n          workspace_id?: number\n",
      ),
    ],
    [
      "Update duplicate field with a different type",
      generatedBody.replace(
        "        Update: {\n          workspace_membership_id?: string\n",
        "        Update: {\n          workspace_membership_id?: string\n          workspace_membership_id: number\n",
      ),
    ],
  ])("fails closed on %s", (_name, malformed) => {
    expect(() => applyTriggerDerivedInsertOptionality(malformed)).toThrow();
  });
});

describe("runGeneratorWithRetry", () => {
  // The Supabase CLI has exited non-zero on a PostHog telemetry timeout with
  // no drift printed (PR #194, 2026-09-02); a green PR was blocked on it.
  // One retry is cheap; a second failure still fails the gate.
  test("a clean first run is not repeated", () => {
    const run = vi.fn(() => ({ status: 0 }));
    const result = runGeneratorWithRetry(run, () => {});
    expect(result.status).toBe(0);
    expect(run).toHaveBeenCalledTimes(1);
  });

  test("a failed first run is retried once and the retry's result wins", () => {
    const run = vi.fn().mockReturnValueOnce({ status: 1 }).mockReturnValueOnce({ status: 0 });
    const logged: string[] = [];
    const result = runGeneratorWithRetry(run, (m: string) => logged.push(m));
    expect(result.status).toBe(0);
    expect(run).toHaveBeenCalledTimes(2);
    expect(logged[0]).toMatch(/retrying once/);
  });

  test("two failures fail the gate", () => {
    const run = vi.fn(() => ({ status: 1 }));
    const result = runGeneratorWithRetry(run, () => {});
    expect(result.status).toBe(1);
    expect(run).toHaveBeenCalledTimes(2);
  });
});
