import type { CellarWineRow } from "./types";

/**
 * Shared CellarWineRow fixture for the drawer's extracted-section tests
 * (pricing / decant / drink-window). Mirrors the `row()` helper in
 * wine-detail-drawer-state.test.tsx — kept here so those colocated tests
 * don't each restate the full row shape.
 */
export function baseRow(overrides: Partial<CellarWineRow> = {}): CellarWineRow {
  return {
    wine_id: "wine-1",
    name: "Test Wine",
    healthSegment: null,
    producer: "Producer",
    vintage: 2024,
    varietal: "Pinot Noir",
    region: "Willamette Valley",
    country: "USA",
    lineage_id: null,
    wine_size_ml: 750,
    duplicate_wine_ids: [],
    is_eightysixed: false,
    eightysixed_at: null,
    tasting_notes: null,
    hero_image_url: null,
    sealed_count: 1,
    bin_location: null,
    bin_placements: [],
    unplaced_count: 0,
    suggested_bin: null,
    section: null,
    wine_list_item_id: null,
    glass_pour_ml: null,
    pour_size_mode: null,
    size_ml: 750,
    open_remaining_ml: 500,
    opened_at: "2026-08-18T10:00:00.000Z",
    open_bottle_id: "bottle-1",
    preservation_method: "coravin",
    opened_by: null,
    theoretical_remaining_ml: 515,
    activeBottleCount: 1,
    activeOpenMl: 500,
    activeBottles: [{
      id: "bottle-1",
      wineId: "wine-1",
      remainingMl: 500,
      nominalCapacityMl: null,
      openedAt: "2026-08-18T10:00:00.000Z",
      preservationMethod: "coravin",
      sourceProvenance: "legacy_unknown",
      sourceBinLocation: null,
      identityContract: 1,
      identityOrigin: "legacy_slot",
      stateVersion: 0,
    }],
    closeout_reason_codes: [],
    stock_adjustment_reason_codes: [],
    drink_window_start: null,
    drink_window_end: null,
    peak_year: null,
    rating: null,
    rating_source: null,
    review_excerpt: null,
    manual_overrides: [],
    colour: null,
    serving_temp_min: null,
    serving_temp_max: null,
    serving_temp_label: null,
    decant_minutes: null,
    retail_min: null,
    retail_max: null,
    retail_median: null,
    retail_retailer_count: null,
    retail_refreshed_at: null,
    current_bottle_price: null,
    current_glass_price: null,
    current_list_name: null,
    current_other_list_count: 0,
    current_unit_cost: null,
    pricing_target_pour_cost_pct: null,
    pricing_target_markup_ratio: null,
    pricing_dismissed_until: null,
    restaurant_default_target_pour_cost_pct: null,
    restaurant_default_target_markup_ratio: null,
    ...overrides,
  };
}
