"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { ActionDialog } from "@/components/action-dialog";
import { useFocusTrap } from "@/lib/hooks/use-focus-trap";

interface QrCodeProps {
  url: string;
}

function QrCode({ url }: QrCodeProps) {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    import("qrcode").then((QRCode) => {
      QRCode.toString(url, {
        type: "svg",
        margin: 1,
        color: { dark: "#1A1A1A", light: "#00000000" },
      }).then((svg) => {
        // Safe: SVG is generated by the qrcode library from a URL we control
        if (containerRef.current) containerRef.current.replaceChildren();
        const parser = new DOMParser();
        const doc = parser.parseFromString(svg, "image/svg+xml");
        const svgEl = doc.documentElement;
        if (containerRef.current) containerRef.current.appendChild(svgEl);
      });
    });
  }, [url]);

  return <div ref={containerRef} className="mx-auto w-[200px]" role="img" aria-label={`QR code linking to ${url}`} />;
}

interface PublishModalProps {
  listId: string;
  listName: string;
  currentSlug: string | null;
  isPublished: boolean;
  onClose: () => void;
}

export function PublishModal({ listId, listName, currentSlug, isPublished, onClose }: PublishModalProps) {
  const [publishing, setPublishing] = useState(false);
  const [slug, setSlug] = useState(currentSlug ?? "");
  const [slugInput, setSlugInput] = useState(currentSlug ?? "");
  const [slugError, setSlugError] = useState<string | null>(null);
  const [slugSuccess, setSlugSuccess] = useState(false);
  const [published, setPublished] = useState(isPublished);
  const [copied, setCopied] = useState(false);
  const [unpublishOpen, setUnpublishOpen] = useState(false);
  const trapRef = useRef<HTMLDivElement>(null);
  useFocusTrap({
    containerRef: trapRef,
    onEscape: onClose,
    paused: unpublishOpen,
  });

  const publicUrl = slug
    ? `${typeof window !== "undefined" ? window.location.origin : ""}/list/${slug}`
    : null;

  const publish = useCallback(async () => {
    setPublishing(true);
    setSlugError(null);
    try {
      const body: Record<string, string> = {};
      const trimmed = slugInput.trim().toLowerCase();
      if (trimmed) body.slug = trimmed;

      const res = await fetch(`/api/wine-lists/${listId}/publish`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      if (res.ok) {
        setSlug((data as { slug: string }).slug);
        setSlugInput((data as { slug: string }).slug);
        setPublished(true);
      } else {
        setSlugError((data as { error?: string }).error ?? "Publish failed.");
      }
    } finally {
      setPublishing(false);
    }
  }, [listId, slugInput]);

  const unpublish = useCallback(async () => {
    setPublishing(true);
    setSlugError(null);
    try {
      const res = await fetch(`/api/wine-lists/${listId}/publish`, {
        method: "DELETE",
      });
      if (!res.ok) {
        let serverMessage: string | undefined;
        try {
          const data = (await res.json()) as { error?: unknown };
          if (typeof data.error === "string") serverMessage = data.error;
        } catch {
          // non-JSON body — fall through to the existing error state
        }
        setSlugError(serverMessage ?? "Unpublish failed.");
        return;
      }
      setPublished(false);
      setSlug("");
      setSlugInput("");
      setUnpublishOpen(false);
    } catch {
      setSlugError("Unpublish failed.");
    } finally {
      setPublishing(false);
    }
  }, [listId]);

  const saveSlug = useCallback(async () => {
    const trimmed = slugInput.trim().toLowerCase();
    if (!trimmed) {
      setSlugError("Slug must not be empty.");
      return;
    }
    if (trimmed === slug) {
      setSlugError(null);
      return;
    }
    setPublishing(true);
    setSlugError(null);
    setSlugSuccess(false);
    try {
      const res = await fetch(`/api/wine-lists/${listId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ slug: trimmed }),
      });
      if (res.ok) {
        setSlug(trimmed);
        setSlugSuccess(true);
        setTimeout(() => setSlugSuccess(false), 2000);
      } else {
        const data = await res.json();
        setSlugError((data as { error?: string }).error ?? "Failed to update slug.");
      }
    } finally {
      setPublishing(false);
    }
  }, [listId, slugInput, slug]);

  const copyUrl = () => {
    if (!publicUrl) return;
    navigator.clipboard.writeText(publicUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadQr = useCallback(async () => {
    if (!publicUrl || !slug) return;
    // PNG (not the inline SVG) so non-technical users can drop it straight
    // into print templates. White background required — the displayed QR
    // uses a transparent background which won't render on light table tents.
    const QRCode = await import("qrcode");
    const dataUrl = await QRCode.toDataURL(publicUrl, {
      margin: 2,
      width: 1024,
      color: { dark: "#1A1A1A", light: "#FFFFFF" },
    });
    const a = document.createElement("a");
    a.href = dataUrl;
    a.download = `wine-list-${slug}-qr.png`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  }, [publicUrl, slug]);

  return (
    // eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-noninteractive-element-interactions -- backdrop-click-to-dismiss is a mouse-only convenience; this dialog already has full keyboard access via useFocusTrap (Escape + a visible Close button).
    <div
      className="fixed inset-0 z-[var(--z-dialog)] flex items-end justify-center bg-scrim p-md sm:items-center"
      role="dialog"
      aria-modal="true"
      aria-labelledby="publish-title"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div
        ref={trapRef}
        data-publish-panel
        className="glass max-h-[calc(100dvh-2rem)] w-full overflow-y-auto overscroll-contain rounded-t-card p-lg pb-[calc(var(--safe-bottom)+var(--spacing-lg))] sm:max-w-[420px] sm:rounded-card sm:pb-lg"
      >
        {!published ? (
          <>
            <h2 id="publish-title" className="font-serif text-subheading font-normal leading-tight text-ink">
              Publish wine list
            </h2>
            <p className="mt-xs text-body-sm text-ink-soft">
              This will create a public page anyone can view. You can unpublish
              at any time.
            </p>

            {/* Slug input */}
            <div className="mt-md">
              <label htmlFor="publish-slug" className="block text-caption font-medium uppercase tracking-[0.18em] text-grey">
                Public URL slug
              </label>
              <p className="mt-2xs text-ledger text-grey">
                Leave blank to auto-generate from your restaurant name.
              </p>
              <div className="mt-sm flex min-h-11 h-[52px] items-center gap-0 rounded-pill border border-rule-strong bg-surface-sunken focus-within:border-accent focus-ring">
                <span className="select-none pl-md text-body-sm text-grey">/list/</span>
                <input
                  id="publish-slug"
                  type="text"
                  value={slugInput}
                  onChange={(e) => {
                    setSlugInput(e.target.value);
                    setSlugError(null);
                  }}
                  placeholder="spring-2026"
                  className="min-h-11 flex-1 bg-transparent px-0 pr-md text-control text-ink outline-none placeholder:text-grey"
                  autoComplete="off"
                  spellCheck={false}
                />
              </div>
              {slugError && !unpublishOpen && (
                <p className="mt-xs text-ledger text-risk-ink" role="alert">
                  {slugError}
                </p>
              )}
            </div>

            <div className="mt-lg flex flex-col-reverse gap-sm sm:flex-row sm:justify-end">
              <button
                type="button"
                onClick={onClose}
                className="min-h-11 rounded-pill border border-rule-strong bg-transparent px-lg text-control font-medium text-ink transition-colors hover:border-accent hover:text-accent focus-ring"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={publish}
                disabled={publishing}
                className="min-h-11 rounded-pill bg-primary px-lg text-control font-semibold text-seal-ink transition-colors hover:bg-primary-hover focus-ring disabled:opacity-60"
              >
                {publishing ? "Publishing..." : "Publish"}
              </button>
            </div>
          </>
        ) : (
          <>
            <h2 id="publish-title" className="font-serif text-subheading font-normal leading-tight text-ink">
              Your wine list is live
            </h2>

            {publicUrl && (
              <div className="mt-lg">
                <QrCode url={publicUrl} />
              </div>
            )}

            {publicUrl && (
              <div className="mt-lg">
                <div className="flex items-center gap-sm rounded-pill border border-rule-strong bg-surface-sunken px-md py-xs">
                  <span className="min-w-0 flex-1 truncate text-ledger text-grey">
                    {publicUrl}
                  </span>
                  <button
                    type="button"
                    onClick={copyUrl}
                    className="inline-flex min-h-11 shrink-0 items-center rounded-pill px-sm py-xs text-ledger font-medium text-accent transition-colors hover:text-ink focus-ring"
                  >
                    {copied ? "Copied!" : "Copy"}
                  </button>
                </div>
                <button
                  type="button"
                  onClick={downloadQr}
                  className="mt-sm inline-flex min-h-11 items-center rounded-pill border border-rule-strong bg-transparent px-md text-ledger font-medium text-ink transition-colors hover:border-accent hover:text-accent focus-ring"
                >
                  Download QR (PNG)
                </button>
              </div>
            )}

            {/* Slug editing for published lists */}
            <div className="mt-md">
              <label htmlFor="edit-slug" className="block text-caption font-medium uppercase tracking-[0.18em] text-grey">
                Slug
              </label>
              <div className="mt-sm flex items-center gap-sm">
                <div className="flex min-h-11 h-[52px] flex-1 items-center gap-0 rounded-pill border border-rule-strong bg-surface-sunken focus-within:border-accent focus-ring">
                  <span className="select-none pl-md text-body-sm text-grey">/list/</span>
                  <input
                    id="edit-slug"
                    type="text"
                    value={slugInput}
                    onChange={(e) => {
                      setSlugInput(e.target.value);
                      setSlugError(null);
                      setSlugSuccess(false);
                    }}
                    className="min-h-11 flex-1 bg-transparent px-0 pr-md text-control text-ink outline-none"
                    autoComplete="off"
                    spellCheck={false}
                  />
                </div>
                <button
                  type="button"
                  onClick={saveSlug}
                  disabled={publishing || slugInput.trim().toLowerCase() === slug}
                  className="min-h-11 shrink-0 rounded-pill border border-rule-strong bg-transparent px-md text-control font-medium text-ink transition-colors hover:border-accent hover:text-accent focus-ring disabled:opacity-40"
                >
                  {publishing ? "..." : "Save"}
                </button>
              </div>
              {slugError && !unpublishOpen && (
                <p className="mt-xs text-ledger text-risk-ink" role="alert">
                  {slugError}
                </p>
              )}
              {slugSuccess && (
                <p className="mt-xs text-ledger text-ready-ink">
                  Slug updated.
                </p>
              )}
            </div>

            <div className="mt-lg flex justify-between items-center">
              <a
                href={publicUrl ?? "#"}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex min-h-11 items-center text-control font-medium text-accent hover:underline"
              >
                Open in new tab
              </a>
              <div className="flex gap-sm">
                <button
                  type="button"
                  onClick={() => {
                    setSlugError(null);
                    setUnpublishOpen(true);
                  }}
                  disabled={publishing}
                  className="min-h-11 rounded-pill border border-rule-strong bg-transparent px-lg text-control font-medium text-ink transition-colors hover:border-accent hover:text-accent focus-ring disabled:opacity-60"
                >
                  {publishing ? "Unpublishing..." : "Unpublish"}
                </button>
                <button
                  type="button"
                  onClick={onClose}
                  className="min-h-11 rounded-pill bg-primary px-lg text-control font-semibold text-seal-ink transition-colors hover:bg-primary-hover focus-ring"
                >
                  Done
                </button>
              </div>
            </div>
          </>
        )}
      </div>

      <ActionDialog
        open={unpublishOpen}
        title="Unpublish list"
        description={`Unpublish "${listName}"? Its public link will stop working immediately.`}
        confirmLabel="Unpublish list"
        busy={publishing}
        onClose={() => setUnpublishOpen(false)}
        onConfirm={unpublish}
      >
        {slugError && (
          <p
            role="alert"
            className="rounded-card border border-risk-ink/30 bg-risk-wash px-sm py-xs text-body-sm text-risk-ink"
          >
            {slugError}
          </p>
        )}
      </ActionDialog>
    </div>
  );
}
